name = "hobbot-worker"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 */6 * * *", "0 0 * * 1"]

[[d1_databases]]
binding = "GRIMOIRE_DB"
database_name = "grimoire-db"
database_id = "3cb1cdee-17af-477c-ab0a-5a18447948ef"

[[d1_databases]]
binding = "HOBBOT_DB"
database_name = "hobbot-db"
database_id = "d91a32f8-670b-46a3-9008-f16224b2f8d7"
migrations_dir = "migrations/hobbot"

[vars]
ENVIRONMENT = "development"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
